@startuml Component Diagram
skinparam BackgroundColor transparent
skinparam componentStyle uml2
node core #LightGray {
   component "Movie" #ForestGreen
   component "User" #Orange
   [User] -> [Movie]
   
}
node UI #LightGray {
   component "MovieRatingApp" #SkyBlue
   component "MovieRatingController" #SkyBlue
   component "RemoteMovingRatingAccess" #White
   [MovieRatingApp] -right-> [MovieRatingController]
   [MovieRatingController] -down-> [Movie]
   [MovieRatingController] ->[User]
   [MovieRatingController] ->[RemoteMovingRatingAccess]

}
node data #LightGray {
    /'Endre navn på denne'/
   component "UserHandler" #Orange
   component "UserRegister" #Orange
   component "MovieHandler" #ForestGreen
   component "MovieRegister" #ForestGreen
   [MovieRegister]-down->[MovieHandler]
   [UserRegister]-down-> [UserHandler]
   [UserRegister] -> [MovieRegister]
   [MovieRegister] -> [Movie]
   [UserRegister] -> [Movie]
   [UserRegister] -> [User]
}
node restapi #LightGray {
    /'Endre navn på denne'/
   component "MovieRatingSpringController" #White
   component "MovieRatingApplication" #White
   [MovieRatingApplication] -left-> [MovieRatingSpringController]
   [MovieRatingSpringController] <-> [RemoteMovingRatingAccess]
   [MovieRatingSpringController] <- [UserRegister]
   [MovieRatingSpringController] <- [MovieRegister]
   [MovieRegister]->[MovieHandler]
   [UserRegister]-down-> [UserHandler]
}
@enduml
