@startuml Sequence Diagram
skinparam maxNoteSize 50
actor       Actor            as actor
participant UI              as ui
participant Controller      as controller
participant RemoteMovieRatingAcces   as remote
participant MovieRatingSpringController   as server
participant MovieRegister   as movreg
participant MovieHandler as movieHandler
database    Database        as database 

activate actor
actor            ->  ui :                "title", "genre"
activate ui
actor            ->  ui :                "Add movie to register"
deactivate actor
ui              ->  controller :        handleAddMovieToRegister()
deactivate ui
activate controller
controller      ->  remote :     addMovie(movie)
deactivate controller
activate remote
remote --> server : HttpRequest to add Movie to server
deactivate remote
activate server 
server -> movreg :     addMovie(movie)
deactivate server
activate movreg



activate movreg
movreg   ->  movreg :     updateMovieList()

alt #SkyBlue movie already exists in register

    movreg   --> actor :          "The movie already exists."
    deactivate movreg
    activate actor

    note over actor
        Movie was already in
        register and could 
        thus not be added.
    end note


else #Orange movie doesn't exist in register
    
    movreg   -> movieHandler :   writeMovieToRegister(movie)
    deactivate movreg
    activate movieHandler
    movieHandler    -> database :       movie
    deactivate movieHandler
    activate database
    note over database
        Movie wasn't already in
        register and could 
        thus be added to file.
        actor recieving feedback 
        is not part of the diagram.
    end note

end

@enduml